### ISSUE TITLE
xmr-stak on ubuntu 18.04 lts using nvidia gtx 560

### ISSUE THREAD

**Issue by bblz** [mechanator/XMR-STAK-CUDA-8-2.7.x#1]
hi. this is my first time ever to post a message on github and i'm not sure if this is the right place to ask a question. i'm not a programmer and i'm trying to understand if what you've posted/released?, i'm not sure what the correct terminology would be, is for an nt platform? i'm trying to run xmr-stak on ubuntu 18.04 lts using nvidia gtx 560 but i'm having issues and get errors. if this is the right place to discuss the issue i will try and provide necessary details. kind regards.

**Comment by mechanator** [comment]
Sorry this repository is for Windows builds only. However, if you go to 
https://github.com/fireice-uk/xmr-stak/issues
They can help resolve you issue with Ubuntu.
Thanks.
