### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fraserbc** [mechanator/XMR-STAK-CUDA-8-2.7.x#2]
I'm running windows 10 and I have a GTX 560 TI installed. I have the Cuda 8 Toolkit installed but when i try and run xmr-stak.exe it gives me this error
[CUDA] Error gpu 0: <C:/temp/source_backup/xmr-stak-2.7.1/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:431
Any help is appreciated,
Fraser

**Comment by mechanator** [comment]
You don't want to install the CUDA 8 toolkit anymore.
Just use the 385.69 driver instead.
Updated to version 2.10.4 for memory leak problem resolution by dev also.
